#!/usr/bin/env node
// embed_ffx.js — re-embed handoff/Handoff.ffx into handoff/Handoff.jsx
//
// Reads the binary .ffx, encodes every byte as a \xHH escape sequence,
// chunks the result into readable lines, and rewrites the embedded
// constant inside Handoff.jsx between the // EMBED:BEGIN and
// // EMBED:END markers.
//
// Run after editing Handoff.ffx in Pseudo Effect Maker (or any time
// the binary changes). Both files should then be committed together.
//
// Usage:
//   node tools/embed_ffx.js
//
// Output:
//   - Updates handoff/Handoff.jsx in place
//   - Prints the embedded byte count and chunk count

const fs = require('fs');
const path = require('path');

const ROOT     = path.resolve(__dirname, '..');
const FFX_PATH = path.join(ROOT, 'handoff', 'Handoff.ffx');
const JSX_PATH = path.join(ROOT, 'handoff', 'Handoff.jsx');

const BEGIN_MARKER = '// EMBED:BEGIN handoff_ffx_binary';
const END_MARKER   = '// EMBED:END handoff_ffx_binary';

const CHUNK_BYTES = 32; // bytes per source line — keeps the .jsx readable

function encodeBytes(buf) {
    // Build chunks of `\xHH` escape sequences. Each byte → 4 chars.
    const lines = [];
    for (let i = 0; i < buf.length; i += CHUNK_BYTES) {
        const slice = buf.slice(i, i + CHUNK_BYTES);
        let s = '';
        for (let j = 0; j < slice.length; j++) {
            const b = slice[j];
            s += '\\x' + (b < 16 ? '0' : '') + b.toString(16).toUpperCase();
        }
        lines.push('        "' + s + '"');
    }
    return lines.join(' +\n');
}

function buildConstant(buf) {
    return [
        BEGIN_MARKER,
        '    // ' + buf.length + ' bytes — generated by tools/embed_ffx.js from handoff/Handoff.ffx',
        '    // Do NOT edit this block by hand. Edit Handoff.ffx in Pseudo Effect Maker',
        '    // and re-run `node tools/embed_ffx.js` to refresh.',
        '    var HANDOFF_FFX_BINARY =',
        encodeBytes(buf) + ';',
        '    ' + END_MARKER
    ].join('\n');
}

function main() {
    if (!fs.existsSync(FFX_PATH)) {
        console.error('ERROR: Handoff.ffx not found at ' + FFX_PATH);
        process.exit(1);
    }
    if (!fs.existsSync(JSX_PATH)) {
        console.error('ERROR: Handoff.jsx not found at ' + JSX_PATH);
        process.exit(1);
    }

    const ffxBytes = fs.readFileSync(FFX_PATH);
    const jsxText  = fs.readFileSync(JSX_PATH, 'utf8');

    const beginIdx = jsxText.indexOf(BEGIN_MARKER);
    const endIdx   = jsxText.indexOf(END_MARKER);

    if (beginIdx === -1 || endIdx === -1) {
        console.error(
            'ERROR: could not find embed markers in Handoff.jsx.\n' +
            '  Expected: ' + BEGIN_MARKER + ' ... ' + END_MARKER + '\n' +
            '  Insert these markers in Handoff.jsx (with the constant\n' +
            '  declaration between them) and re-run.'
        );
        process.exit(1);
    }

    // Find the start of the line containing BEGIN, and the end of the line containing END
    let lineStart = beginIdx;
    while (lineStart > 0 && jsxText[lineStart - 1] !== '\n') lineStart--;

    let lineEnd = endIdx + END_MARKER.length;
    while (lineEnd < jsxText.length && jsxText[lineEnd] !== '\n') lineEnd++;

    // Preserve indent of the BEGIN marker line
    const indent = jsxText.slice(lineStart, beginIdx);
    const newBlock = buildConstant(ffxBytes)
        .split('\n')
        .map((ln, i) => (i === 0 ? indent + ln : ln))
        .join('\n');

    const newJsx = jsxText.slice(0, lineStart) + newBlock + jsxText.slice(lineEnd);
    fs.writeFileSync(JSX_PATH, newJsx);

    const chunkLines = encodeBytes(ffxBytes).split('\n').length;
    console.log('Embedded ' + ffxBytes.length + ' bytes into Handoff.jsx');
    console.log('  ' + chunkLines + ' chunk lines, ' + CHUNK_BYTES + ' bytes per chunk');
    console.log('  Final .jsx size: ' + fs.statSync(JSX_PATH).size + ' bytes');

    // Also copy the FFX to the CEP extension's assets folder so the
    // bundled copy stays in sync with the source of truth.
    const CEP_ASSETS = path.join(ROOT, 'handoff', 'cep', 'com.aetools.handoff', 'assets');
    const CEP_FFX = path.join(CEP_ASSETS, 'Handoff.ffx');
    if (fs.existsSync(CEP_ASSETS)) {
        fs.copyFileSync(FFX_PATH, CEP_FFX);
        console.log('  Copied to ' + path.relative(ROOT, CEP_FFX));
    }
}

main();
